global:
  edition: ce
  hosts:
    domain: gitlab.local
    externalIP: ubuntu-s-2vcpu-8gb-160gb-intel-nyc1-01  # Use your VM's hostname
    hostname: gitlab.local
  ingress:
    configureCertmanager: false
    enabled: true
    tls:
      enabled: false

gitlab:
  webservice:
    replicas: 1
    ingress:
      tls:
        enabled: false

nginx-ingress:
  enabled: true
  controller:
    replicaCount: 1
    service:
      type: NodePort  # Changed from LoadBalancer
      nodePorts:
        http: 30010
        https: 30011
    hostNetwork: true  # Added for better host connectivity
  defaultBackend:
    enabled: true

certmanager:
  install: false

prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false