global:
  edition: ce

gitlab:
  webservice:
    replicas: 1
    ingress:
      configureCertmanager: false
      tls:
        enabled: false
      annotations:
        kubernetes.io/ingress.class: "nginx"
      hosts:
        - name: 167.172.153.84.nip.io
          path: /
          tls: false

nginx-ingress:
  enabled: true
  controller:
    replicaCount: 1
    service:
      type: NodePort
      sessionAffinity: "ClientIP"  # <-- FIX: Enable session affinity
      nodePorts:
        http: 30010
        https: 30011
  defaultBackend:
    enabled: true

certmanager:
  install: false

certmanager-issuer:
  email: "your-email@example.com"

prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false
