global:
  edition: ce
  hosts:
    domain: gitlab.local
    externalIP: <your-vm-public-ip>
    hostname: gitlab.local
  ingress:
    configureCertmanager: false
    enabled: true
    tls:
      enabled: false

gitlab:
  webservice:
    replicas: 1
    ingress:
      tls:
        enabled: false

nginx-ingress:
  enabled: true
  controller:
    replicaCount: 1
    service:
      type: NodePort
      nodePorts:
        http: 30010
        https: 30011
  defaultBackend:
    enabled: true

certmanager:
  install: false

prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false
