global:
  edition: ce
  hosts:
    domain: gitlab.local
    externalIP: 127.0.0.1
    hostname: gitlab.local
  ingress:
    configureCertmanager: false
    enabled: true
    class: nginx
    tls:
      enabled: false

nginx-ingress:
  enabled: true
  controller:
    service:
      type: NodePort
      nodePorts:
        http: 30080
    hostPort:
      enabled: true
      ports:
        http: 80
  defaultBackend:
    enabled: true

certmanager:
  install: false

prometheus:
  install: false

grafana:
  enabled: false

gitlab-runner:
  install: false

