Vagrant.configure("2") do |config|
    config.vm.box = "debian/bookworm64"
  
    config.vm.define "zaabouS" do |vm|
      vm.vm.hostname = "zaabouS"
      vm.vm.network "private_network", ip: "192.168.56.110"
      vm.vm.provider "virtualbox" do |vb|
        vb.memory = 1024
        vb.cpus = 1
      end
      vm.vm.provision "shell", path: "scripts/install_k3s_and_apps.sh"
    end
  end
  